---
# The most valuable linters; they are required to pass for PR to be merged.

run:
  modules-download-mode: readonly

linters-settings:
  goimports:
    local-prefixes: github.com/AlekSi/applehealth

linters:
  disable-all: true
  enable:
    - exhaustive
    - goimports
    - govet
    - ineffassign
    - staticcheck

issues:
  exclude-use-default: false
