// Code generated by crete (https://github.com/AlekSi/crete). DO NOT EDIT.

// +build tools

package tools // import "github.com/AlekSi/applehealth/tools"

import (
	_ "github.com/golangci/golangci-lint/cmd/golangci-lint"
	_ "github.com/quasilyte/go-consistent"
	_ "golang.org/x/perf/cmd/benchstat"
	_ "mvdan.cc/gofumpt/gofumports"
)
