---
name: Go
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Test
    strategy:
      matrix:
        go-version:
          - 1.14.x
          - 1.15.x
    runs-on: ubuntu-20.04

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        run: make test

  golangci-lint:
    name: golangci-lint
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run required linters
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.35 # sync with tools/go.mod
          args: --config=.golangci-required.yml
          only-new-issues: false
          # skip-go-installation: true

      - name: Run all linters
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.35 # sync with tools/go.mod
          args: --config=.golangci.yml
          only-new-issues: true
          # skip-go-installation: true
