---
name: Linters
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  golangci-lint:
    name: golangci-lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run required linters
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.31
          only-new-issues: false
          args: --config=.golangci-required.yml

      - name: Run all linters
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.31
          only-new-issues: true
          args: --config=.golangci.yml
